pipeline {
   agent any
   stages {
      stage('Environment Sate') {
               
         steps {
            echo "Build  Environmentt level"
            sh "ls -l"
            sh "cat abc.txt"
        }
      }
   
      stage('VM Sate') {
       
         steps {
            echo "Build VM  level"
            sh "ls -l"
            
            sh "cat abc.txt"
         }
      }
       
       
   }
}
